rmdir Build\vs2008\Debug /S/Q
del *.~* /s
del *~ /s
del *.pch /s
del *.obj /s
del *.idb /s
del *.ilk /s
del *.pdb /s
del *.exp /s
del *.ddp /s
del *.ncb /s
del *.opt /s
del *.positions /s
del *.user /s
del *.idb /s
del BuildLog.htm /s
del *.intermediate.manifest /s
del mt.dep /s
del *.suo /a/s
del *.exe /s